### ISSUE TITLE
Can create flights with no departure time

### ISSUE THREAD

**Issue by J-C-V** [MetaEMK/FGK_PASMAS_backend#31]
### Endpoint
flights/planning

### Method
POST

### Description
If there is no flight yet, you can create one without departure time. Else you get a slot error.

![Image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/6b04d2cc-a2f0-4e8d-b51e-972afe1d1007)

### Steps to reproduce
Sending a request with only plane id.

### Expected behaviour:
Backend throws missing parameter error.

**Comment by MetaEMK** [comment]
Will be fixed in next release (v0.3)

**Comment by MetaEMK** [comment]
fixed in v0.2.1
