### ISSUE TITLE
No SSE on flight delete

### ISSUE THREAD

**Issue by J-C-V** [MetaEMK/FGK_PASMAS_backend#41]
### Version
main

### Endpoint
/realtime/flights

### Method
GET

### Description
Client doesn't receive a SSE on flight delete although the deletion is successful.

![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/ed8666cb-4ff2-4675-ae3a-245b58f09a53)

![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/a407314b-285f-4faa-b7bd-74abaa18439d)

### Steps to reproduce
Deleting an existing flight.

### Expected behaviour:
Server sends SSE on delete.

**Comment by MetaEMK** [comment]
What version is this?
I have tested it and on v0.3 with commit ed0a944 it worked fine.
Can you possibly give me more information about the problem?

![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/23456557/4192cb3a-b3e7-4901-9d80-8b4f47ad9b4a)

- Version name
- Flight data to be deleted
- Exact response of the backend in the call and in the realtime event
- If possible also the server logs
