### ISSUE TITLE
Missing features 4.0

### ISSUE THREAD

**Issue by J-C-V** [MetaEMK/FGK_PASMAS_backend#47]
- [x] Slot interval for each plane endpoint
- [x] Create user with role endpoint
- [x] Get all users
- [x] Delete user
- [x] Ticket ID on booking success
- [x] Realtime endpoint for all flights (Currently responds with 404)
- [x] POST, PATCH and SSEs should always return the full resource with all sub resources
- [x] Add query parameter option to GET /flights to only get upcoming flights (departure time > now)

**Comment by J-C-V** [comment]
Updated missing feature list

**Comment by MetaEMK** [comment]
Create user with role endpoint implemented in v0.4

**Comment by MetaEMK** [comment]
> Updated missing feature list

passenger or flight?

**Comment by J-C-V** [comment]
Ticket No. of each passenger.

Updated missing feature list.

**Comment by J-C-V** [comment]
Updated missing feature list
