### ISSUE TITLE
Can't set preferred pilot to certain pilots

### ISSUE THREAD

**Issue by J-C-V** [MetaEMK/FGK_PASMAS_backend#53]
### API Version

v0.5.0

### Endpoint

planes/:id

### Method

PATCH

### Description

Can't set a preferred pilot although they are eligible.

### Steps to reproduce

Send PATCH request with plane ID 7 and set PrefPilotId to 3.

![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/78ed4b58-a8ea-48d1-a822-a6e6a9d03fe3)

### Expected behaviour

Set the preferred pilot because they are listed in the available pilot list. They're also literally the current preferred pilot:

![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/76563632-eabe-418d-9fff-dc35a1497e89)

![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/2d18dff7-a678-4db7-9695-c0d3ac13a150)

**Comment by MetaEMK** [comment]
implemented and fixed
